<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwRrimx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwRrimx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQwRrimx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQwRrimx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQwRrimx\App_KernelProdContainer([
    'container.build_hash' => 'QwRrimx',
    'container.build_id' => '2147ec80',
    'container.build_time' => 1669229623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwRrimx');
