<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'app_admin_send_newsletter' => [[], ['_controller' => 'App\\Controller\\AdminController::sendNewsletter'], [], [['text', '/admin/sendNewsletter']], [], [], []],
    'Mails' => [[], ['_controller' => 'App\\Controller\\AdminController::dowloadletter'], [], [['text', '/admin/dowloadMails']], [], [], []],
    'app_employe' => [[], ['_controller' => 'App\\Controller\\EmployeController::employe'], [], [['text', '/employe']], [], [], []],
    'gains' => [[], ['_controller' => 'App\\Controller\\EmployeController::gains'], [], [['text', '/gains']], [], [], []],
    'app_code_send' => [[], ['_controller' => 'App\\Controller\\EmployeController::codeSend'], [], [['text', '/employe/codeSend']], [], [], []],
    'app_check_customer' => [[], ['_controller' => 'App\\Controller\\EmployeController::employeCheckuser'], [], [['text', '/employe/checkuser/checkcode']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_bienvenu' => [[], ['_controller' => 'App\\Controller\\HomeController::bienvenu'], [], [['text', '/bienvenu']], [], [], []],
    'app_code_cadeau_check' => [[], ['_controller' => 'App\\Controller\\HomeController::codecadeauCheck'], [], [['text', '/codecadeau/check']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
