<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWKtYxdx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWKtYxdx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWKtYxdx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWKtYxdx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWKtYxdx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WKtYxdx',
    'container.build_id' => 'eaf70f81',
    'container.build_time' => 1669229395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWKtYxdx');
